# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_auto_20170411_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to='pages.Page')),
            ],
            options={
                'verbose_name': 'Extra Info',
                'verbose_name_plural': 'Extra Info',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('file', mezzanine.core.fields.FileField(max_length=200, verbose_name='File')),
                ('description', models.CharField(blank=True, max_length=70, verbose_name='Description')),
                ('link_text', models.CharField(blank=True, max_length=70, null=True, verbose_name='Link text')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('size_text', models.CharField(choices=[('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('h5', 'h5')], max_length=5, verbose_name='Size')),
                ('extra_description', models.TextField(blank=True, null=True)),
                ('resize', models.BooleanField(verbose_name='Resize')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='pages.Page')),
            ],
            options={
                'ordering': ['_order'],
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
    ]
